'use strict';
const http = require('http'), fs = require('fs'), path = require('path'), crypto = require('crypto');
const { execFile } = require('child_process');
(function loadEnv(f) { try { for (const l of fs.readFileSync(f, 'utf8').split(/\r?\n/)) { const m = l.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*?)\s*$/); if (m && !(m[1] in process.env)) process.env[m[1]] = m[2].replace(/^["']|["']$/g, ''); } } catch { /* no .env */ } })(path.join(__dirname, '..', '.env'));
const { chat, status } = require('./router'); const orch = require('./orchestrator');
const PUBLIC = path.join(__dirname, '..', 'public'), UP = path.join(orch.DATA, 'uploads'); fs.mkdirSync(UP, { recursive: true });
const MIME = { html: 'text/html; charset=utf-8', css: 'text/css', js: 'text/javascript', json: 'application/json', svg: 'image/svg+xml', png: 'image/png', jpg: 'image/jpeg', txt: 'text/plain', md: 'text/plain', ico: 'image/x-icon' };
const httpErr = (status, message) => Object.assign(new Error(message), { status }); const send = (res, code, obj) => { res.writeHead(code, { 'Content-Type': 'application/json', 'Cache-Control': 'no-store' }); res.end(JSON.stringify(obj)); };
async function body(req, max = 15e6) { let n = 0; const c = []; for await (const x of req) { n += x.length; if (n > max) throw httpErr(413, 'Payload too large'); c.push(x); } try { return JSON.parse(Buffer.concat(c).toString() || '{}'); } catch { throw httpErr(400, 'Invalid JSON'); } }
function authed(req) { const t = process.env.APP_TOKEN; if (!t) return true; const got = Buffer.from((req.headers.authorization || '').replace(/^Bearer /, '')); const want = Buffer.from(t); return got.length === want.length && crypto.timingSafeEqual(got, want); }
function serve(res, root, rel, extra = {}) { let f; try { f = orch.safeJoin(root, rel.replace(/^\/+/, '') || 'index.html'); } catch { res.writeHead(400); return res.end('Bad path'); } if (fs.existsSync(f) && fs.statSync(f).isDirectory()) f = path.join(f, 'index.html'); fs.readFile(f, (e, data) => { if (e) { res.writeHead(404); return res.end('Not found'); } res.writeHead(200, { 'Content-Type': MIME[path.extname(f).slice(1)] || 'application/octet-stream', 'X-Content-Type-Options': 'nosniff', ...extra }); res.end(data); }); }
const safeName = (n) => String(n || '').replace(/[^\w.\- ]/g, '_').slice(0, 120); function fileContext(names = []) { return names.slice(0, 10).map((n) => { const f = path.join(UP, safeName(n)); if (!fs.existsSync(f)) return ''; if (/\.zip$/i.test(f)) return `Uploaded ZIP ${n} (listing available only; extraction is not performed)`; const s = fs.readFileSync(f, 'utf8'); return `<<<UPLOADED ${n}>>>\n${s.slice(0, 15000)}\n<<<END>>>`; }).filter(Boolean).join('\n'); }
async function route(req, res) { const p = new URL(req.url, 'http://x').pathname, m = req.method; if (p.startsWith('/preview/')) { const mm = p.match(/^\/preview\/([a-f0-9]{16})(\/.*)?$/); if (!mm) throw httpErr(404, 'Not found'); return serve(res, path.join(orch.WS, mm[1]), mm[2] || '/', { 'Content-Security-Policy': 'sandbox allow-scripts' }); } if (!p.startsWith('/api/')) return serve(res, PUBLIC, p); if (p === '/api/health') return send(res, 200, { ok: true, auth: !!process.env.APP_TOKEN }); if (!authed(req)) throw httpErr(401, 'Unauthorized: set the access token in Settings'); if (p === '/api/providers' && m === 'GET') return send(res, 200, { providers: status() }); if (p === '/api/chat' && m === 'POST') { const b = await body(req); if (!Array.isArray(b.messages) || !b.messages.length) throw httpErr(400, 'messages required'); const msgs = b.messages.slice(-30).map((x) => ({ role: x.role === 'assistant' ? 'assistant' : 'user', content: String(x.content).slice(0, 20000) })); const r = await chat(msgs); return send(res, 200, { text: r.text, provider: r.provider, model: r.model, attempts: r.attempts }); } if (p === '/api/tasks' && m === 'POST') { const b = await body(req); const t = orch.createTask(b.goal, fileContext(b.files)); return send(res, 202, { id: t.id }); } if (p === '/api/tasks' && m === 'GET') return send(res, 200, { tasks: orch.listTasks() }); let mm = p.match(/^\/api\/tasks\/([a-f0-9]{16})(\/deploy)?$/); if (mm) { if (!mm[2] && m === 'GET') return send(res, 200, orch.getTask(mm[1])); if (mm[2] && m === 'GET') return send(res, 200, orch.manifest(mm[1])); if (mm[2] && m === 'POST') return send(res, 200, orch.deploy(mm[1], await body(req))); } if (p === '/api/files' && m === 'GET') return send(res, 200, { files: fs.readdirSync(UP).map((n) => ({ name: n, bytes: fs.statSync(path.join(UP, n)).size })) }); if (p === '/api/files' && m === 'POST') { const b = await body(req, 20e6); const name = safeName(b.name); if (!name || typeof b.content !== 'string') throw httpErr(400, 'name and base64 content required'); const buf = Buffer.from(b.content, 'base64'); fs.writeFileSync(path.join(UP, name), buf); if (/\.zip$/i.test(name)) return execFile('unzip', ['-l', path.join(UP, name)], { timeout: 10000 }, (e, out) => send(res, 200, { name, bytes: buf.length, listing: e ? 'unzip unavailable' : out.split('\n').slice(0, 200).join('\n') })); return send(res, 200, { name, bytes: buf.length }); } throw httpErr(404, 'Not found'); }
const createServer = () => http.createServer((req, res) => route(req, res).catch((e) => { if (res.headersSent) return res.end(); send(res, e.status || 500, { error: e.message, code: e.code, attempts: e.attempts }); })); module.exports = { createServer }; if (require.main === module) { const port = +process.env.PORT || 3000, host = process.env.HOST || '127.0.0.1'; createServer().listen(port, host, () => { console.log(`NONONICK AI on http://${host}:${port}`); if (!process.env.APP_TOKEN && host !== '127.0.0.1') console.warn('WARNING: APP_TOKEN is not set but the server is network-reachable.'); if (!status().some((p) => p.configured)) console.warn('No AI provider configured - see .env.example'); }); }
